-- Migration 0001 — initial schema
-- Generated from specs/02-data-model.md (approved final version).
-- D1 / SQLite.
--
-- Conventions:
--   * TEXT primary keys (UUIDs, generated by the Worker via crypto.randomUUID()).
--     `pricing_components` is the one exception — uses `code` as its natural PK.
--   * Booleans:   INTEGER NOT NULL CHECK (col IN (0, 1)).
--   * Timestamps: TEXT (ISO 8601, millisecond precision via strftime).
--   * Status / enum columns: TEXT with CHECK constraint.
--   * Polymorphic refs (audit_log.entity_id, document_signature.document_id):
--     no FK constraint; integrity is enforced in application code.
--   * No updated_at columns by design — spec 02 doesn't call for them. Will be
--     added selectively in a later migration when live sync is wired.

------------------------------------------------------------------------
-- admin_user
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_user (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  email           TEXT NOT NULL UNIQUE,
  password_hash   TEXT NOT NULL,                                            -- bcrypt, 12 rounds
  role            TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'sales', 'delivery')),
  active          INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  last_login_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_admin_user_email  ON admin_user(email);
CREATE INDEX IF NOT EXISTS idx_admin_user_active ON admin_user(active);

------------------------------------------------------------------------
-- admin_session
-- Separate from portal_session by design (different TTLs, security posture).
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_session (
  id                TEXT PRIMARY KEY,
  admin_user_id     TEXT NOT NULL REFERENCES admin_user(id) ON DELETE CASCADE,
  session_token     TEXT NOT NULL UNIQUE,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  last_active_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  expires_at        TEXT NOT NULL,                                          -- created_at + 24h
  idle_expires_at   TEXT NOT NULL,                                          -- last_active_at + 12h
  ip_address        TEXT,
  user_agent        TEXT,
  revoked_at        TEXT
);
CREATE INDEX IF NOT EXISTS idx_admin_session_token   ON admin_session(session_token);
CREATE INDEX IF NOT EXISTS idx_admin_session_user    ON admin_session(admin_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_session_expires ON admin_session(expires_at);

------------------------------------------------------------------------
-- chat_session
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_session (
  id                    TEXT PRIMARY KEY,
  session_token         TEXT NOT NULL UNIQUE,
  started_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  last_active_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  source_page           TEXT,
  visitor_fingerprint   TEXT,
  status                TEXT NOT NULL DEFAULT 'active'
                          CHECK (status IN ('active', 'abandoned', 'captured_as_lead'))
);
CREATE INDEX IF NOT EXISTS idx_chat_session_token  ON chat_session(session_token);
CREATE INDEX IF NOT EXISTS idx_chat_session_status ON chat_session(status);
CREATE INDEX IF NOT EXISTS idx_chat_session_active ON chat_session(last_active_at);

------------------------------------------------------------------------
-- chat_message
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chat_message (
  id           TEXT PRIMARY KEY,
  session_id   TEXT NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
  role         TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content      TEXT NOT NULL,
  tool_calls   TEXT,                                                        -- JSON array of Claude tool calls
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_chat_message_session ON chat_message(session_id, created_at);

------------------------------------------------------------------------
-- lead
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lead (
  id                        TEXT PRIMARY KEY,
  name                      TEXT,
  email                     TEXT,
  phone                     TEXT,
  company                   TEXT,
  industry                  TEXT,
  source                    TEXT CHECK (source IS NULL OR source IN ('chat', 'manual', 'referral', 'event')),
  origin_chat_session_id    TEXT REFERENCES chat_session(id) ON DELETE SET NULL,
  pain_summary              TEXT,
  urgency                   TEXT CHECK (urgency IS NULL OR urgency IN ('immediate', 'weeks', 'months', 'exploring')),
  status                    TEXT NOT NULL DEFAULT 'new'
                              CHECK (status IN ('new', 'reviewed', 'contacted', 'qualified', 'disqualified', 'converted')),
  notes                     TEXT,
  notification_sent_at      TEXT,                                           -- set on first qualifying save_lead notification
  owner_user_id             TEXT REFERENCES admin_user(id) ON DELETE SET NULL,
  last_contacted_at         TEXT,
  created_at                TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_lead_status        ON lead(status);
CREATE INDEX IF NOT EXISTS idx_lead_email         ON lead(email);
CREATE INDEX IF NOT EXISTS idx_lead_origin_chat   ON lead(origin_chat_session_id);
CREATE INDEX IF NOT EXISTS idx_lead_owner         ON lead(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_lead_created       ON lead(created_at);

------------------------------------------------------------------------
-- client
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS client (
  id                      TEXT PRIMARY KEY,
  company_name            TEXT NOT NULL,
  primary_contact_name    TEXT,
  primary_contact_email   TEXT,
  primary_contact_phone   TEXT,
  industry                TEXT,
  billing_address         TEXT,
  status                  TEXT NOT NULL DEFAULT 'prospect'
                            CHECK (status IN ('prospect', 'active', 'paused', 'former')),
  origin_lead_id          TEXT REFERENCES lead(id) ON DELETE SET NULL,
  notes                   TEXT,
  created_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_client_status      ON client(status);
CREATE INDEX IF NOT EXISTS idx_client_company     ON client(company_name);
CREATE INDEX IF NOT EXISTS idx_client_origin_lead ON client(origin_lead_id);

------------------------------------------------------------------------
-- opportunity
-- presentation_token: unguessable token used at /p/:token/, declared in spec 02.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS opportunity (
  id                      TEXT PRIMARY KEY,
  client_id               TEXT NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  name                    TEXT NOT NULL,
  description             TEXT,
  status                  TEXT NOT NULL DEFAULT 'open'
                            CHECK (status IN ('open', 'proposed', 'accepted', 'lost', 'paused')),
  value_setup             REAL,
  value_monthly           REAL,
  next_followup_date      TEXT,
  presentation_token      TEXT NOT NULL UNIQUE,
  owner_user_id           TEXT REFERENCES admin_user(id) ON DELETE SET NULL,
  accepted_at             TEXT,
  lost_reason             TEXT,
  created_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_opportunity_client   ON opportunity(client_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_status   ON opportunity(status);
CREATE INDEX IF NOT EXISTS idx_opportunity_token    ON opportunity(presentation_token);
CREATE INDEX IF NOT EXISTS idx_opportunity_owner    ON opportunity(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_followup ON opportunity(next_followup_date);

------------------------------------------------------------------------
-- pricing_components (live rate card)
-- Natural PK on `code`. Seed data lives in /data/pricing-components.csv
-- and will be loaded in migration 0002.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pricing_components (
  code          TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  description   TEXT,
  category      TEXT NOT NULL
                  CHECK (category IN ('table', 'role', 'workflow', 'integration',
                                      'ai', 'dashboard', 'setup', 'subscription', 'custom')),
  unit_type     TEXT NOT NULL
                  CHECK (unit_type IN ('flat_setup', 'per_item_setup',
                                       'flat_monthly', 'per_item_monthly',
                                       'setup_and_monthly')),
  unit_price    REAL NOT NULL,
  active        INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_pricing_active   ON pricing_components(active);
CREATE INDEX IF NOT EXISTS idx_pricing_category ON pricing_components(category);

------------------------------------------------------------------------
-- portal_account
-- Created here (before change_order / contract) so their FKs to it work
-- cleanly when foreign_keys pragma is enforced at INSERT time.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portal_account (
  id                       TEXT PRIMARY KEY,
  client_id                TEXT NOT NULL UNIQUE REFERENCES client(id) ON DELETE CASCADE,
  email                    TEXT NOT NULL UNIQUE,
  password_hash            TEXT NOT NULL,                                   -- bcrypt, 12 rounds
  must_change_password     INTEGER NOT NULL DEFAULT 1 CHECK (must_change_password IN (0, 1)),
  walkthrough_completed    INTEGER NOT NULL DEFAULT 0 CHECK (walkthrough_completed IN (0, 1)),
  walkthrough_state        TEXT NOT NULL DEFAULT 'new'
                             CHECK (walkthrough_state IN ('new', 'password_set',
                                                          'contract_signed', 'payment_set',
                                                          'complete')),
  created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  last_login_at            TEXT
);
CREATE INDEX IF NOT EXISTS idx_portal_account_email  ON portal_account(email);
CREATE INDEX IF NOT EXISTS idx_portal_account_client ON portal_account(client_id);

------------------------------------------------------------------------
-- portal_session
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portal_session (
  id                  TEXT PRIMARY KEY,
  portal_account_id   TEXT NOT NULL REFERENCES portal_account(id) ON DELETE CASCADE,
  session_token       TEXT NOT NULL UNIQUE,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  last_active_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  expires_at          TEXT NOT NULL,                                        -- created_at + 90d
  idle_expires_at     TEXT NOT NULL,                                        -- last_active_at + 30d
  ip_address          TEXT,
  user_agent          TEXT,
  revoked_at          TEXT
);
CREATE INDEX IF NOT EXISTS idx_portal_session_token   ON portal_session(session_token);
CREATE INDEX IF NOT EXISTS idx_portal_session_account ON portal_session(portal_account_id);
CREATE INDEX IF NOT EXISTS idx_portal_session_expires ON portal_session(expires_at);

------------------------------------------------------------------------
-- proposal
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proposal (
  id                          TEXT PRIMARY KEY,
  opportunity_id              TEXT NOT NULL REFERENCES opportunity(id) ON DELETE CASCADE,
  name                        TEXT NOT NULL,
  status                      TEXT NOT NULL DEFAULT 'draft'
                                CHECK (status IN ('draft', 'sent', 'accepted', 'superseded', 'declined')),
  setup_total                 REAL NOT NULL DEFAULT 0,
  monthly_total               REAL NOT NULL DEFAULT 0,

  -- Presentation content (rendered on /p/:token/ via the public data endpoint)
  narrative_challenge         TEXT,
  narrative_solution          TEXT,
  key_capabilities            TEXT,                                         -- JSON array of strings
  pricing_display_mode        TEXT NOT NULL DEFAULT 'summary'
                                CHECK (pricing_display_mode IN ('summary', 'categorical', 'full')),
  demo_enabled                INTEGER NOT NULL DEFAULT 0 CHECK (demo_enabled IN (0, 1)),

  -- Modifiers (mutable in draft/sent, immutable on acceptance)
  modifiers                   TEXT,                                         -- JSON: { complexity_multiplier, urgency_multiplier, custom_discount_percent, ... }

  notes                       TEXT,                                         -- admin-internal
  presentation_notes          TEXT,                                         -- sales conversation notes; copied to project on activation, then frozen here
  cloned_from_proposal_id     TEXT REFERENCES proposal(id) ON DELETE SET NULL,

  created_at                  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  sent_at                     TEXT,
  accepted_at                 TEXT
);
CREATE INDEX IF NOT EXISTS idx_proposal_opportunity   ON proposal(opportunity_id);
CREATE INDEX IF NOT EXISTS idx_proposal_status        ON proposal(status);
CREATE INDEX IF NOT EXISTS idx_proposal_cloned_from   ON proposal(cloned_from_proposal_id);
CREATE INDEX IF NOT EXISTS idx_proposal_created       ON proposal(created_at);  -- staleness queries

------------------------------------------------------------------------
-- pricing_snapshot
-- Immutable from creation. snapshot_at = proposal.created_at, set once.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pricing_snapshot (
  id              TEXT PRIMARY KEY,
  proposal_id     TEXT NOT NULL UNIQUE REFERENCES proposal(id) ON DELETE CASCADE,
  snapshot_data   TEXT NOT NULL,                                            -- JSON: full rate card freeze
  snapshot_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

------------------------------------------------------------------------
-- proposal_line_item
-- component_code is intentionally NOT FK-constrained to pricing_components(code):
--   * 'custom_line_item' is a wildcard for free-form lines.
--   * Historical line items must survive component deactivation.
--   * The actual rate is frozen in unit_price_at_snapshot.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proposal_line_item (
  id                       TEXT PRIMARY KEY,
  proposal_id              TEXT NOT NULL REFERENCES proposal(id) ON DELETE CASCADE,
  component_code           TEXT NOT NULL,                                   -- soft ref to pricing_components.code
  quantity                 REAL NOT NULL DEFAULT 1,
  unit_price_at_snapshot   REAL NOT NULL,
  line_total               REAL NOT NULL,
  description_override     TEXT,
  created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_proposal_line_proposal ON proposal_line_item(proposal_id);

------------------------------------------------------------------------
-- change_order
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS change_order (
  id                              TEXT PRIMARY KEY,
  proposal_id                     TEXT NOT NULL REFERENCES proposal(id) ON DELETE CASCADE,
  name                            TEXT NOT NULL,
  status                          TEXT NOT NULL DEFAULT 'draft'
                                    CHECK (status IN ('draft', 'proposed', 'approved', 'rejected', 'withdrawn')),
  reason                          TEXT,
  setup_delta                     REAL NOT NULL DEFAULT 0,
  monthly_delta                   REAL NOT NULL DEFAULT 0,
  proposed_at                     TEXT,
  approved_at                     TEXT,
  approved_by_portal_account_id   TEXT REFERENCES portal_account(id) ON DELETE SET NULL,
  created_at                      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_change_order_proposal ON change_order(proposal_id);
CREATE INDEX IF NOT EXISTS idx_change_order_status   ON change_order(status);

------------------------------------------------------------------------
-- change_order_line_item
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS change_order_line_item (
  id                         TEXT PRIMARY KEY,
  change_order_id            TEXT NOT NULL REFERENCES change_order(id) ON DELETE CASCADE,
  action                     TEXT NOT NULL CHECK (action IN ('add', 'remove')),
  component_code             TEXT NOT NULL,                                 -- soft ref to pricing_components.code
  quantity                   REAL NOT NULL DEFAULT 1,
  unit_price_from_snapshot   REAL NOT NULL,
  line_total_delta           REAL NOT NULL,
  description_override       TEXT,
  created_at                 TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_co_line_co ON change_order_line_item(change_order_id);

------------------------------------------------------------------------
-- project
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS project (
  id                    TEXT PRIMARY KEY,
  opportunity_id        TEXT NOT NULL UNIQUE REFERENCES opportunity(id) ON DELETE CASCADE,
  name                  TEXT NOT NULL,
  status                TEXT NOT NULL DEFAULT 'kickoff'
                          CHECK (status IN ('kickoff', 'active', 'paused', 'complete', 'canceled')),
  presentation_notes    TEXT,                                               -- snapshot copy from proposal at creation, then living document
  build_status_note     TEXT,
  current_phase         TEXT,
  next_milestone        TEXT,
  created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  kicked_off_at         TEXT,
  completed_at          TEXT
);
CREATE INDEX IF NOT EXISTS idx_project_status ON project(status);

------------------------------------------------------------------------
-- contract
-- Signer reached via contract.opportunity_id → opportunity.client_id → client → portal_account.
-- signed_by_portal_account_id captures who actually signed (validated in app code to match).
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contract (
  id                             TEXT PRIMARY KEY,
  opportunity_id                 TEXT NOT NULL UNIQUE REFERENCES opportunity(id) ON DELETE CASCADE,
  template_version               TEXT NOT NULL,
  body_source                    TEXT NOT NULL,                             -- JSON: { template_path, variables }
  body_html                      TEXT NOT NULL,
  generated_at                   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  signed_at                      TEXT,
  signed_by_portal_account_id    TEXT REFERENCES portal_account(id) ON DELETE SET NULL,
  pdf_r2_key                     TEXT
);

------------------------------------------------------------------------
-- document_signature
-- Polymorphic: document_id targets contract / change_order / etc.
-- No FK on document_id by design — see spec 02 Critical Relationship #13.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS document_signature (
  id                  TEXT PRIMARY KEY,
  portal_account_id   TEXT NOT NULL REFERENCES portal_account(id) ON DELETE CASCADE,
  document_type       TEXT NOT NULL CHECK (document_type IN ('contract', 'change_order', 'amendment', 'other')),
  document_id         TEXT NOT NULL,                                        -- polymorphic ref, no FK
  signature_type      TEXT NOT NULL CHECK (signature_type IN ('signature', 'initial', 'agreement_acceptance')),
  typed_name          TEXT,
  typed_initials      TEXT,
  ip_address          TEXT,
  user_agent          TEXT,
  opportunity_id      TEXT NOT NULL REFERENCES opportunity(id) ON DELETE CASCADE,
  signed_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_doc_sig_portal_account ON document_signature(portal_account_id);
CREATE INDEX IF NOT EXISTS idx_doc_sig_document       ON document_signature(document_type, document_id);
CREATE INDEX IF NOT EXISTS idx_doc_sig_opportunity    ON document_signature(opportunity_id);

------------------------------------------------------------------------
-- stripe_customer
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stripe_customer (
  id                    TEXT PRIMARY KEY,
  client_id             TEXT NOT NULL UNIQUE REFERENCES client(id) ON DELETE CASCADE,
  stripe_customer_id    TEXT NOT NULL UNIQUE,
  created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

------------------------------------------------------------------------
-- stripe_subscription
-- opportunity_id is the operational key; client_id is denormalized.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stripe_subscription (
  id                          TEXT PRIMARY KEY,
  client_id                   TEXT NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  opportunity_id              TEXT NOT NULL REFERENCES opportunity(id) ON DELETE CASCADE,
  stripe_subscription_id      TEXT NOT NULL UNIQUE,
  status                      TEXT NOT NULL CHECK (status IN ('active', 'past_due', 'canceled')),
  current_amount_monthly      REAL NOT NULL,
  current_period_end          TEXT,
  created_at                  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_stripe_sub_opportunity ON stripe_subscription(opportunity_id);
CREATE INDEX IF NOT EXISTS idx_stripe_sub_client      ON stripe_subscription(client_id);
CREATE INDEX IF NOT EXISTS idx_stripe_sub_status      ON stripe_subscription(status);

------------------------------------------------------------------------
-- stripe_invoice
-- opportunity_id is the operational key; client_id is denormalized.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stripe_invoice (
  id                      TEXT PRIMARY KEY,
  client_id               TEXT NOT NULL REFERENCES client(id) ON DELETE CASCADE,
  opportunity_id          TEXT NOT NULL REFERENCES opportunity(id) ON DELETE CASCADE,
  stripe_invoice_id       TEXT NOT NULL UNIQUE,
  kind                    TEXT NOT NULL CHECK (kind IN ('setup', 'change_order_setup', 'other')),
  amount                  REAL NOT NULL,
  status                  TEXT NOT NULL,
  paid_at                 TEXT,
  created_at              TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_stripe_inv_opportunity ON stripe_invoice(opportunity_id);
CREATE INDEX IF NOT EXISTS idx_stripe_inv_client      ON stripe_invoice(client_id);
CREATE INDEX IF NOT EXISTS idx_stripe_inv_status      ON stripe_invoice(status);

------------------------------------------------------------------------
-- calling_list_item
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS calling_list_item (
  id                  TEXT PRIMARY KEY,
  company_name        TEXT NOT NULL,
  contact_name        TEXT,
  contact_email       TEXT,
  contact_phone       TEXT,
  industry            TEXT,
  source              TEXT,
  call_date           TEXT NOT NULL,                                        -- YYYY-MM-DD
  status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'called', 'completed',
                                          'no_answer', 'followup',
                                          'disqualified', 'converted_to_lead')),
  notes               TEXT,
  extra_data          TEXT,                                                 -- JSON: unmapped CSV columns
  converted_lead_id   TEXT REFERENCES lead(id) ON DELETE SET NULL,
  imported_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_calling_item_date    ON calling_list_item(call_date);
CREATE INDEX IF NOT EXISTS idx_calling_item_status  ON calling_list_item(status);
CREATE INDEX IF NOT EXISTS idx_calling_item_company ON calling_list_item(company_name);

------------------------------------------------------------------------
-- calling_log
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS calling_log (
  id                      TEXT PRIMARY KEY,
  calling_list_item_id    TEXT NOT NULL REFERENCES calling_list_item(id) ON DELETE CASCADE,
  called_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  outcome                 TEXT NOT NULL
                            CHECK (outcome IN ('no_answer', 'left_voicemail',
                                               'spoke_not_interested', 'spoke_followup_needed',
                                               'disqualified', 'spoke_qualified')),
  notes                   TEXT,
  next_action_date        TEXT
);
CREATE INDEX IF NOT EXISTS idx_calling_log_item ON calling_log(calling_list_item_id);

------------------------------------------------------------------------
-- audit_log
-- entity_id is polymorphic; no FK by design.
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
  id            TEXT PRIMARY KEY,
  actor_type    TEXT NOT NULL CHECK (actor_type IN ('admin_user', 'portal_account', 'system')),
  actor_id      TEXT,                                                       -- nullable for 'system' actor
  action        TEXT NOT NULL,
  entity_type   TEXT NOT NULL,
  entity_id     TEXT NOT NULL,                                              -- polymorphic ref, no FK
  changes       TEXT,                                                       -- JSON diff
  ip_address    TEXT,
  user_agent    TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_audit_entity  ON audit_log(entity_type, entity_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_actor   ON audit_log(actor_type, actor_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);

------------------------------------------------------------------------
-- notification
------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notification (
  id           TEXT PRIMARY KEY,
  kind         TEXT NOT NULL
                 CHECK (kind IN ('new_lead', 'walkthrough_complete',
                                 'change_order_proposed', 'change_order_approved',
                                 'payment_succeeded', 'payment_failed',
                                 'activation_credentials', 'project_status_update',
                                 'other')),
  recipient    TEXT NOT NULL,
  channel      TEXT NOT NULL CHECK (channel IN ('email', 'sms', 'in_app')),
  payload      TEXT,                                                        -- JSON
  status       TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'sent', 'failed')),
  error        TEXT,
  sent_at      TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX IF NOT EXISTS idx_notification_kind   ON notification(kind, created_at);
CREATE INDEX IF NOT EXISTS idx_notification_status ON notification(status);
